spring:
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create   # <-- ACÁ ESTÁ EL CAMBIO
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false